### ISSUE TITLE
Can't set inference in transactional repository client

### ISSUE THREAD

**Issue by svilenvelikov** [Ontotext-AD/graphdb.js#202]
**Library version [3.0.2]**

**Node.js version [18]**

**Describe the bug**
setInference(false) does not work when it is used in a transactionClient.

**Comment by DesiBorisova** [comment]
@LesterLyu could you please provide the query you were testing setInference(false) with in the TransactionalRepositoryClient? More specifically, I'm interested in the content-type.

**Comment by LesterLyu** [comment]
The content type is set to `QueryContentType.SPARQL_QUERY`:
```js

const client = getRepositoryClient();
const transactionClient = await client.beginTransaction();
transactionClient.registerParser(new JsonLDParser());

const query = `some-query`
const payload = new GetQueryPayload()
    .setQuery(query)
    .setQueryType(QueryType.CONSTRUCT)
    .setResponseType(RDFMimeType.JSON_LD)
    .setInference(false)
    .setContentType(QueryContentType.SPARQL_QUERY)

const result = [];
const stream = await transactionClient.query(payload);

stream.on('data', (bindings) => {
    result.push(bindings);
});

await transactionClient.commit()
```

**Comment by DesiBorisova** [comment]
We have implemented a fix with https://github.com/Ontotext-AD/graphdb.js/pull/205

**Comment by LesterLyu** [comment]
The update does not seem to fix the issue.


### Insert some triples
```js
const client = getRepositoryClient();

const insertQuery = `
  PREFIX ex: <http://example.com/>
  PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
  INSERT data {
    ex:Place a rdfs:Class .
    ex:BusStop a rdfs:Class .
    ex:BusStop rdfs:subClassOf ex:Place .
    
    ex:busstop a ex:BusStop .
  }`;
    
const payload = new UpdateQueryPayload()
  .setQuery(insertQuery)
  .setContentType(QueryContentType.SPARQL_UPDATE)
  .setTimeout(5);

await client.update(payload);
```

### Should construct without inference in a transaction
```js
const client = getRepositoryClient();
const transactionClient = await client.beginTransaction();
transactionClient.registerParser(new JsonLDParser());

const query = `
  PREFIX ex: <http://example.com/>
  PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
  construct where {
      ex:busstop a ?type.
  }
`
const payload = new GetQueryPayload()
    .setQuery(query)
    .setQueryType(QueryType.CONSTRUCT)
    .setResponseType(RDFMimeType.JSON_LD)
    .setInference(false)
    .setContentType(QueryContentType.SPARQL_QUERY)

const result = [];
const stream = await transactionClient.query(payload);

stream.on('data', (bindings) => {
    result.push(bindings);
});

// With inference turned off, there should be only one result.
expect(result).length(1);
```

**Comment by DesiBorisova** [comment]
I apologize, due to a mistake on our side, the fix did not make it in version 3.0.3. We have released a new version (3.0.4). Please let us know if the issue persists. Apologies again.
